services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_USER:-postgres}
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-26T23:58:00'
      environment: development
      stage: '1-database'
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: app_db
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - redis-cli ping
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-26T23:58:00'
      environment: development
      stage: '1-cache'
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data

  api:
    image: python:3.11-slim
    restart: unless-stopped
    command: |
      sh -c "pip install flask psycopg2-binary redis &&
      python -c '
      from flask import Flask, jsonify
      import os, socket
      app = Flask(__name__)

      @app.route(\"/health\")
      def health():
          return jsonify({\"status\": \"healthy\", \"host\": socket.gethostname()})

      @app.route(\"/api/status\")
      def status():
          return jsonify({\"service\": \"api\", \"version\": \"1.0\", \"db\": \"postgres\", \"cache\": \"redis\"})

      if __name__ == \"__main__\":
          app.run(host=\"0.0.0.0\", port=5000)
      '"
    healthcheck:
      test:
      - CMD-SHELL
      - "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5000/health')\" || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-26T23:58:00'
      environment: development
      stage: '2-backend'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://devops:${DB_PASSWORD:-changeme}@postgres:5432/app_db
      REDIS_URL: redis://redis:6379/0
      FLASK_ENV: development
    ports:
    - 5000:5000

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost/
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-26T23:58:00'
      environment: development
      stage: '3-frontend'
    depends_on:
      api:
        condition: service_healthy
    ports:
    - 8080:80
    volumes:
    - nginx_config:/etc/nginx/conf.d

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nginx_config:
    driver: local
