services:
  db:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_USER:-postgres}
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-27T00:04:14'
      environment: development
      stage: 1-database
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
    volumes:
    - db_postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-27T00:04:14'
      environment: development
      stage: 1-cache
    ports:
    - 6379:6379
    volumes:
    - cache_redis_data:/data
  api:
    image: python:3.11-slim
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - exit 0
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-27T00:04:14'
      environment: development
      stage: 2-backend
    ports:
    - 5000:5000
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  web:
    image: nginx:alpine
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost/
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-27T00:04:14'
      environment: development
      stage: 3-proxy
    ports:
    - 8080:80
    depends_on:
      api:
        condition: service_healthy
    volumes:
    - web_nginx_config:/etc/nginx/conf.d
    - web_nginx_html:/usr/share/nginx/html
networks:
  app_network:
    driver: bridge
volumes:
  db_postgres_data:
    driver: local
  cache_redis_data:
    driver: local
  web_nginx_config:
    driver: local
  web_nginx_html:
    driver: local
