services:
  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
    - app_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      managed-by: docker-devops-agent
      created-at: '2026-02-27T19:35:14'
      environment: development
      stage: 1-cache
    ports:
    - 6380:6379
    volumes:
    - redis_data:/data
networks:
  app_network:
    driver: bridge
volumes:
  redis_data:
    driver: local
